### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by spanchenko** [IS2AI/Kazakh_TTS#1]
Dear IS2AI,
In page https://issai.nu.edu.kz/ru/tts-rus/ you say that dataset is available upon request. I've wrote request to your contact email issai@nu.edu.kz several days before but haven't got reply.

Could you please provide answer on my request or provide access to dataset in response to this issue?

Thanks a lot

**Comment by mussakhojayeva** [comment]
Hi! Dataset distribution starts today.
