### ISSUE TITLE
Google form to access the dataset is not working

### ISSUE THREAD

**Issue by cweaver-logitech** [IS2AI/Kazakh_TTS#13]
Hello,

I would like to download this dataset and have tried filling out the Google form: https://docs.google.com/forms/d/e/1FAIpQLSf4vlv2NAV2dA8QL2V_uQZHOUENY6SR87n_9xToSEHX5oylVA/viewform

The form does not seem to accept answers given for "Brief Purpose"
![image](https://github.com/IS2AI/Kazakh_TTS/assets/87655550/879935a9-4173-4e95-9835-694e278c3656)

**Comment by mussakhojayeva** [comment]
Hi, please try more than 150 characters, should work. We will fix google form text soon!

**Comment by cweaver-logitech** [comment]
Thanks for quick reply. Yes, adding more than 150 characters worked fine.

**Comment by cweaver-logitech** [comment]
Could you tell me what Kazakh dataset this is: https://www.openslr.org/140/
![image](https://github.com/IS2AI/Kazakh_TTS/assets/87655550/95c581bd-69f6-4c88-8e8e-d436ecc14d2f)
I'd like to find the paper detailing it's creation.

Many thanks.

**Comment by mussakhojayeva** [comment]
We are not related to this work. Please try writing to the authors.
