### ISSUE TITLE
Pretrained models not available

### ISSUE THREAD

**Issue by tugstugi** [IS2AI/Kazakh_TTS#3]
Hi,

the linked pretrained models like `https://issai.nu.edu.kz/wp-content/uploads/2021/04/kaztts_male1_tacotron2_train.loss.ave.zip` can't be downloaded. The links forward to the main page.

greetings

**Comment by mussakhojayeva** [comment]
Hi, 
We are currently making revisions. I will notify you here once the links become available.

**Comment by Erkebulant** [comment]
https://user-images.githubusercontent.com/96575715/147234973-b7f481cc-0a2a-4020-b81e-fe9586f8cf26.mp4
