### ISSUE TITLE
Where to get the models from README.md?

### ISSUE THREAD

**Issue by dexXxed** [IS2AI/Kazakh_TTS#6]
Hello, I want to test your repo on my data to make text2speach, but I have an issue

I have installed all properly, but I do not understand where to get following models:

```
## specify the path to vocoder's checkpoint, i.e 
vocoder_checkpoint="exp/vocoder/checkpoint-400000steps.pkl" 

## specify path to the main model(transformer/tacotron2/fastspeech) and its config file 
config_file = "exp/tts_train_raw_char/config.yaml" 
model_path = "exp/tts_train_raw_char/train.loss.ave_5best.pth"
```

Can you please provide links where to download these models? 

Thank you very much!

Waiting for your reply!

**Comment by mussakhojayeva** [comment]
Hi! I've updated the README, you can find the links there

**Comment by dexXxed** [comment]
Thank you! have a nice day!
