### ISSUE TITLE
Pretrained model without CUDA

### ISSUE THREAD

**Issue by codionysus** [IS2AI/Kazakh_TTS#8]
Hi,
I would like test your TTS and use it without CUDA if it's possible.
Could you give me an example of synthesizer with pretrained model and without cuda?
Thanks

**Comment by mussakhojayeva** [comment]
Hi! 
This could be done by modifying tts1/synthesize.py line 30 to "cpu"

**Comment by codionysus** [comment]
Hi,
what about line 20? That gives error that pytorch was build without cuda

**Comment by mussakhojayeva** [comment]
Similarly just change line to either cpu, or to() completely.

**Comment by codionysus** [comment]
Hi, 
I have tested both options and it gives me an error on [line 47](https://github.com/IS2AI/Kazakh_TTS/blob/32ce655770a4f158fb3696100b8ad4ec521eb23f/tts1/synthesize.py#L47): TypeError: new(): invalid data type 'str'.
I execute this command:
python synthesize.py --text "бүгінде өңірде тағы бес жобаның құрылысы жүргізілуде."

**Comment by rodion-m** [comment]
To make it work, in the file `synthesize.py` change this:
```python
with torch.no_grad():
    _, c_mel, *_ = text2speech(sample_text.lower())
    wav = vocoder.inference(c_mel)
```
to this:
```python
with torch.no_grad():
    output_dict = text2speech(sample_text.lower())
    feat_gen = output_dict['feat_gen']
    wav = vocoder.inference(feat_gen)
```
Here is a PR: #10
