### ISSUE TITLE
Web API for TTS

### ISSUE THREAD

**Issue by rodion-m** [IS2AI/Kazakh_TTS#9]
Hello. Thanks for this project! I was wondering is there any web API for Kazakh TTS? (send text to the endpoint, get audio)

**Comment by mussakhojayeva** [comment]
Hello ~
We do not provide an API

**Comment by rodion-m** [comment]
Ok, thanks. I made a Web API for Kazakh TTS that is based on your project: https://github.com/rodion-m/kazakh_text2speach_web_api \
Perhaps it'll help someone.
